SELECT * FROM ERS_USER ORDER BY USER_ID;
SELECT * FROM ERS_REIMBURSEMENT ORDER BY REIMB_ID;
SELECT * FROM ERS_REIMB_STATUS ORDER BY REIMB_STATUS_ID;
SELECT * FROM ERS_REIMB_TYPE ORDER BY REIMB_TYPE_ID;
SELECT * FROM ERS_USER_ROLES ORDER BY USER_ROLE_ID;

INSERT INTO ERS_REIMBURSEMENT(REIMB_AMOUNT,REIMB_SUBMITTED,REIMB_RESOLVED,REIMB_DESCRIPTION,REIMB_RECEIPT,REIMB_AUTHOR,REIMB_RESOLVER,
REIMB_STATUS_ID,REIMB_TYPE_ID) 
VALUES(50,CURRENT_TIMESTAMP,null,'Stay at Reston Marriott Hotel',null,1,null,1,1);
commit;

INSERT INTO ERS_USER(USERNAME,PW,FIRSTNAME,LASTNAME,USER_EMAIL,USER_ROLE_ID) 
VALUES('employee','password','Test','Employee','test@revature.com',1);
commit;

INSERT INTO ERS_USER(USERNAME,PW,FIRSTNAME,LASTNAME,USER_EMAIL,USER_ROLE_ID) 
VALUES('manager','password','Test','Manager','manager@revature.com',2);

INSERT INTO ERS_REIMB_STATUS(REIMB_STATUS) 
VALUES('Denied');
commit;

INSERT INTO ERS_REIMB_TYPE(REIMB_TYPE) 
VALUES('Food');
commit;

INSERT INTO ERS_USER_ROLES(USER_ROLE) 
VALUES('Manager');
commit;