CREATE TABLE ERS_REIMBURSEMENT(
 REIMB_ID NUMBER(10)PRIMARY KEY,
 REIMB_AMOUNT NUMBER(10) NOT NULL,
 REIMB_SUBMITTED TIMESTAMP(4) NOT NULL,
 REIMB_RESOLVED TIMESTAMP(4),
 REIMB_DESCRIPTION VARCHAR2(50),
 REIMB_RECEIPT BLOB,
 REIMB_AUTHOR NUMBER(10) NOT NULL,
 REIMB_RESOLVER NUMBER(10),
 REIMB_STATUS_ID NUMBER(10) NOT NULL,
 REIMB_TYPE_ID NUMBER(10) NOT NULL,
 FOREIGN KEY(REIMB_STATUS_ID) REFERENCES ERS_REIMB_STATUS(REIMB_STATUS_ID),
 FOREIGN KEY(REIMB_TYPE_ID) REFERENCES ERS_REIMB_TYPE(REIMB_TYPE_ID),
 FOREIGN KEY(REIMB_AUTHOR) REFERENCES ERS_USER(ERS_USER_ID),
 FOREIGN KEY(REIMB_RESOLVER) REFERENCES ERS_USER(ERS_USER_ID)
);

CREATE TABLE ERS_USER(
 ERS_USER_ID NUMBER(10) PRIMARY KEY,
 ERS_USERNAME VARCHAR2(50) NOT NULL UNIQUE,
 ERS_PASSWORD VARCHAR2(50) NOT NULL,
 ERS_FIRSTNAME VARCHAR2(50) NOT NULL,
 ERS_LASTNAME VARCHAR2(50),
 USER_EMAIL VARCHAR2(50) NOT NULL UNIQUE,
 USER_ROLE_ID NUMBER NOT NULL,
 FOREIGN KEY(USER_ROLE_ID) REFERENCES ERS_USER_ROLES(USER_ROLE_ID)
);

CREATE TABLE ERS_REIMB_STATUS(
 REIMB_STATUS_ID NUMBER(10) PRIMARY KEY,
 REIMB_STATUS VARCHAR2(10) NOT NULL
);

CREATE TABLE ERS_REIMB_TYPE(
 REIMB_TYPE_ID NUMBER(10) PRIMARY KEY,
 REIMB_TYPE VARCHAR2(10) NOT NULL
);

CREATE TABLE ERS_USER_ROLES(
 USER_ROLE_ID NUMBER(10) PRIMARY KEY,
 USER_ROLE VARCHAR2(10) NOT NULL
);
