SELECT * FROM ERS_USER ORDER BY USER_ID;
SELECT * FROM ERS_REIMBURSEMENT ORDER BY REIMB_ID;
SELECT * FROM ERS_REIMB_STATUS ORDER BY REIMB_STATUS_ID;
SELECT * FROM ERS_REIMB_TYPE ORDER BY REIMB_TYPE_ID;
SELECT * FROM ERS_USER_ROLES ORDER BY USER_ROLE_ID;

INSERT INTO ERS_REIMBURSEMENT(REIMB_AMOUNT,REIMB_SUBMITTED,REIMB_RESOLVED,REIMB_DESCRIPTION,REIMB_AUTHOR,REIMB_RESOLVER,
REIMB_STATUS_ID,REIMB_TYPE_ID) 
VALUES(10,CURRENT_TIMESTAMP,null,'McDonalds',1,null,2,3);
commit;

DELETE FROM ERS_REIMBURSEMENT WHERE REIMB_ID > 127;

DELETE FROM ERS_USER WHERE USER_ID > 2;

rollback;

INSERT INTO ERS_USER(USERNAME,PW,FIRSTNAME,LASTNAME,USER_EMAIL,USER_ROLE_ID) 
VALUES('employee','password','Test','Employee','test@revature.com',1);
commit;

SELECT * FROM ERS_REIMBURSEMENT WHERE REIMB_TYPE_ID != 1;

INSERT INTO ERS_USER(USERNAME,PW,FIRSTNAME,LASTNAME,USER_EMAIL,USER_ROLE_ID) 
VALUES('emp','pass','Test','User2','emp@revature.com',1);

INSERT INTO ERS_REIMB_STATUS(REIMB_STATUS) 
VALUES('Denied');
commit;

INSERT INTO ERS_REIMB_TYPE(REIMB_TYPE) 
VALUES('Food');
commit;

INSERT INTO ERS_USER_ROLES(USER_ROLE) 
VALUES('Manager');
commit;