CREATE TABLE ERS_REIMBURSEMENT_STATUS(
REIMB_STATUS_ID NUMBER NOT NULL,
REIMB_STATUS VARCHAR2(10),
PRIMARY KEY (REIMB_STATUS_ID) 
);
CREATE TABLE ERS_REIMBURSEMENT_TYPE(
REIMB_TYPE_ID NUMBER,
REIMB_TYPE VARCHAR2(10),
PRIMARY KEY (REIMB_TYPE_ID)
);
CREATE TABLE ERS_USER_ROLES(
ERS_USER_ROLE_ID NUMBER,
USER_ROLE VARCHAR2(10),
PRIMARY KEY (ERS_USER_ROLE_ID)
);
CREATE TABLE ERS_USERS(
ERS_USERS_ID NUMBER,
ERS_USERNAME VARCHAR2(50) UNIQUE,
ERS_PASSWORD VARCHAR2(50),
USER_FIRST_NAME VARCHAR2(100),
USER_LAST_NAME VARCHAR2(100),
USER_EMAIL VARCHAR2(150) UNIQUE,
USER_ROLE_ID NUMBER,
PRIMARY KEY (ERS_USERS_ID),
FOREIGN KEY (USER_ROLE_ID) REFERENCES ERS_USER_ROLES(ERS_USER_ROLE_ID)
);
CREATE TABLE ERS_REIMBURSEMENT(
REIMB_ID NUMBER,
REIMB_AMOUNT NUMBER,
REIM_SUBMITTED TIMESTAMP,
REIMB_RESOLVED TIMESTAMP,
REIMB_DESCRIPTION VARCHAR2(250),
REIMB_RECEIPT BLOB,
REIMB_AUTHOR NUMBER,
REIMB_RESOLVER NUMBER,
REIMB_STATUS_ID NUMBER,
REIMB_TYPE_ID NUMBER,
PRIMARY KEY (REIMB_ID),
FOREIGN KEY (REIMB_AUTHOR) REFERENCES ERS_USERS(ERS_USERS_ID),
FOREIGN KEY (REIMB_RESOLVER) REFERENCES ERS_USERS(ERS_USERS_ID),
FOREIGN KEY (REIMB_STATUS_ID) REFERENCES ERS_REIMBURSEMENT_STATUS(REIMB_STATUS_ID),
FOREIGN KEY (REIMB_TYPE_ID) REFERENCES ERS_REIMBURSEMENT_TYPE(REIMB_TYPE_ID)
);

DROP TABLE  ERS_REIMBURSEMENT_STATUS;
DROP TABLE ERS_REIMBURSEMENT_TYPE;
DROP TABLE ERS_USER_ROLES;
DROP TABLE ERS_USERS;
DROP TABLE ERS_REIMBURSEMENT;
