CREATE TABLE ERS_REIMBURSMENT(
    REIMB_ID NUMBER Primary Key,
    REIMB_AMOUNT NUMBER,
    REIMB_SUBMITTED TIMESTAMP,
    REIMB_RESOLVED TIMESTAMP,
    REIMB_DESCRIPTION VARCHAR2(250),
    REIMB_RECEIPT BLOB,
    REIMB_AUTHOR NUMBER,
    REIMB_RESOLVER NUMBER,
    REIMB_STATUS_ID NUMBER,
    REIM_TYPE_ID NUMBER,
    FOREIGN KEY (REIMB_AUTHOR) REFERENCES ERS_USERS (ERS_USERS_FK_AUTH),
    FOREIGN KEY (REIMB_RESOLVER) REFERENCES ERS_USERS (ERS_USERS_FK_RESLVR),
    FOREIGN KEY (REIMB_STATUS_ID) REFERENCES ERS_REIMBURSMENT_STATUS (ERS_REIMBUSRTMENT_STATUS_FK),
    FOREIGN KEY (REIM_TYPE_ID) REFERENCES ERS_REIMBURSMENT_TYPE(ERS_REIMBURSTMENT_TYPE_FK)
    
);

CREATE TABLE ERS_USERS(
    ERS_USERS_ID NUMBER Primary Key,
    ERS_USERNAME VARCHAR2(50) UNIQUE,
    ERS_PASSWORD VARCHAR2(50),
    USER_FIRST_NAME VARCHAR2(100),
    USER_LAST_NAME VARCHAR2(100),
    USER_EMAIL VARCHAR2(150) UNIQUE,
    USER_ROLE_ID NUMBER,
    ERS_USERS_FK_AUTH NUMBER,
    ERS_USERS_FK_RESLVR NUMBER,
    FOREIGN KEY (USER_ROLE_ID) REFERENCES ERS_USER_ROLES(USER_ROLES_FK)
);



CREATE TABLE ERS_REIMBURSMENT_STATUS(
    REIMB_STATUS_ID NUMBER Primary Key,
    REIM_STATUS VARCHAR2(10),
    ERS_REIMBURSMENT_STATUS_FK NUMBER
);

CREATE TABLE ERS_REIMBURSMENT_TYPE(
    REIM_TYPE_ID NUMBER Primary Key,
    REIM_TYPE VARCHAR2(10),
    ERS_REIMBURSMENT_TYPE_FK NUMBER
);

CREATE TABLE ERS_USER_ROLES( 
    ERS_USER_ROLE_ID NUMBER Primary Key,
    USER_ROLE VARCHAR2(10),
    USER_ROLES_FK NUMBER
);