/*
2.1 SELECT

A) SELECT * FROM EMPLOYEE;
B) SELECT * FROM  EMPLOYEE WHERE LASTNAME = 'King';
C) SELECT * FROM  EMPLOYEE WHERE FIRSTNAME = 'Andrew' AND REPORTSTO IS NULL;
*/

/*
2.2 ORDER BY

A) SELECT * FROM ALBUM ORDER BY TITLE DESC;
B) SELECT FIRSTNAME FROM CUSTOMER ORDER BY CITY
*/

SELECT * FROM ALBUM ORDER BY TITLE DESC;