/* DDL (Data Definition Language) Script for Book Store (Barnes & Noble) Example
Will contain a Genre, Book, Author table
*/

--CREATE TABLE [table name] ([column info][table level constraints]);
CREATE TABLE BN_GENRE(
  GENRE_ID NUMBER(10) PRIMARY KEY,
  NAME VARCHAR2(36) NOT NULL UNIQUE 
);

CREATE TABLE BN_AUTHOR(
  AUTHOR_ID NUMBER(10) PRIMARY KEY,
  FIRST_NAME VARCHAR2(50) NOT NULL,
  LAST_NAME VARCHAR2(50),
  BIO VARCHAR2(1000)
);

CREATE TABLE BN_BOOK(
  BOOK_ID NUMBER(10) PRIMARY KEY, 
  ISBN VARCHAR2(10) UNIQUE NOT NULL,
  AUTHOR NUMBER(10) NOT NULL,
  TITLE VARCHAR2(256) NOT NULL,
  PRICE NUMBER(6,2) NOT NULL,
  GENRE NUMBER(10) NOT NULL,
  CONSTRAINT FK_BOOK_GENRE --NOT NECESSARY TO NAME CONSTRAINTS BUT YOU CAN
  FOREIGN KEY(GENRE) REFERENCES BN_GENRE(GENRE_ID),
  FOREIGN KEY(AUTHOR) REFERENCES BK_AUTHOR(AUTHOR_ID)
);