import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'squareroot' // ie {{ 10 | squareroot}
})
export class SquarerootPipe implements PipeTransform {
/*
  //must override transform  method -- method stub autogenerated with ng g p
  transform(value: any, args?: any): any {
    return null;
  } */

   transform(value: number): number {
    return Math.sqrt(value);
  }

}
