CREATE OR REPLACE TRIGGER BI_ACCOUNT
BEFORE INSERT ON ACCOUNT
FOR EACH ROW
BEGIN 
    SELECT ACCOUNT_AI.NEXTVAL INTO :NEW.ACCOUNTID FROM DUAL;
END;
/

INSERT INTO CUSTOMER(USERNAME, PASSWORD) VALUES('jross','123450');
INSERT INTO ACCOUNT(ACCOUNTTYPE, BALANCE, USERID) VALUES('Checking','500.00','1');

CREATE or REPLACE FUNCTION TESTY(USER_ID IN NUMBER)
RETURN NUMBER
IS
 return_val NUMBER;
BEGIN
    SELECT COUNT(*) into return_val FROM ACCOUNT WHERE USERID = USER_ID;
    return return_val;
END;
/

SELECT TESTY FROM DUAL;

UPDATE ACCOUNT SET BALANCE = 300 WHERE ACCOUNTID = 3 AND BALANCE = 300.00